 p : with p; [
             AC-Vector
             #Agda
             BlastHTTP 
             BlogLiterately 
             BlogLiterately-diagrams 
             Boolean 
             BoundedChan 
             Cabal 
             Cabal-ide-backend 
             Chart 
             Chart-cairo 
             Chart-diagrams 
             ChasingBottoms 
             ConfigFile 
             DAV 
             DRBG 
             Decimal 
             Diff 
             Earley 
             FenwickTree 
             FontyFruity 
             GenericPretty 
             Glob 
             GraphSCC 
             HCodecs 
             HList 
             HStringTemplate 
             HTF 
             HTTP 
             HUnit 
             HaTeX 
             HaXml 
             HandsomeSoup 
             HaskellNet 
             HsOpenSSL 
             IOSpec 
             IPv6Addr 
             IfElse 
             JuicyPixels 
             List 
             ListLike 
             MemoTrie 
             MissingH 
             MonadCatchIO-transformers 
             MonadPrompt 
             MonadRandom 
             Network-NineP 
             NineP 
             NumInstances 
             Octree 
             OneTuple 
             PSQueue 
             QuasiText 
             QuickCheck 
             QuickCheck-safe 
             RSA 
             Rasterific 
             ReadArgs 
             RefSerialize 
             Rlang-QQ 
             SHA 
             STMonadTrans 
             SVGFonts 
             SafeSemaphore 
             Spock 
             Spock-digestive 
             Spock-worker 
             StateVar 
             Stream 
             TCache 
             Unixutils 
             #Win32 
             #Win32-notify 
             Workflow 
             X11 
             Yampa 
             YampaSynth 
             abstract-deque 
             abstract-par 
             accelerate 
             ace 
             acid-state 
             action-permutations 
             active 
             ad 
             adjunctions 
             aeson 
             aeson-better-errors 
             aeson-pretty 
             aeson-qq 
             aeson-schema 
             aeson-utils 
             agentx 
             alarmclock 
             alex 
             amazonka 
             amazonka-autoscaling 
             amazonka-cloudformation 
             amazonka-cloudfront 
             amazonka-cloudhsm 
             amazonka-cloudsearch 
             amazonka-cloudsearch-domains 
             amazonka-cloudtrail 
             amazonka-cloudwatch 
             amazonka-cloudwatch-logs 
             amazonka-codedeploy 
             amazonka-cognito-identity 
             amazonka-cognito-sync 
             amazonka-config 
             amazonka-core 
             amazonka-datapipeline 
             amazonka-directconnect 
             amazonka-dynamodb 
             amazonka-ec2 
             amazonka-ecs 
             amazonka-elasticache 
             amazonka-elasticbeanstalk 
             amazonka-elastictranscoder 
             amazonka-elb 
             amazonka-emr 
             amazonka-glacier 
             amazonka-iam 
             amazonka-importexport 
             amazonka-kinesis 
             amazonka-kms 
             amazonka-lambda 
             amazonka-ml 
             amazonka-opsworks 
             amazonka-rds 
             amazonka-redshift 
             amazonka-route53 
             amazonka-route53-domains 
             amazonka-s3 
             amazonka-sdb 
             amazonka-ses 
             amazonka-sns 
             amazonka-sqs 
             amazonka-ssm 
             amazonka-storagegateway 
             amazonka-sts 
             amazonka-support 
             amazonka-swf 
             amazonka-workspaces 
             amqp 
             angel 
             annotated-wl-pprint 
             anonymous-sums 
             ansi-terminal 
             ansi-wl-pprint 
             apiary 
             apiary-authenticate 
             apiary-clientsession 
             apiary-cookie 
             apiary-eventsource 
             apiary-logger 
             apiary-memcached 
             apiary-mongoDB 
             apiary-persistent 
             apiary-session 
             apiary-websockets 
             appar 
             applicative-quoters 
             approximate 
             arbtt 
             arrow-list 
             arrows 
             asciidiagram 
             asn1-encoding 
             asn1-parse 
             asn1-types 
             async 
             atomic-primops 
             attoparsec 
             attoparsec-enumerator 
             attoparsec-expr 
             attoparsec-trans 
             authenticate 
             authenticate-oauth 
             auto 
             auto-update 
             aws 
             b9 
             bake 
             bank-holidays-england 
             base-compat 
             base-orphans 
             base-prelude 
             base-unicode-symbols 
             base16-bytestring 
             base32string 
             base58string 
             base64-bytestring 
             base64-string 
             basic-prelude 
             bcrypt 
             bencode 
             bifunctors 
             binary-conduit 
             binary-list 
             binary-search 
             bindings-DSL 
             bioace 
             bioalign 
             biocore 
             biofasta 
             biofastq 
             biopsl 
             #bitcoin-api 
             #bitcoin-api-extra 
             #bitcoin-block 
             #bitcoin-script 
             #bitcoin-tx 
             #bitcoin-types 
             bits 
             bitwise 
             blastxml 
             blaze-builder 
             blaze-builder-enumerator 
             blaze-html 
             blaze-markup 
             blaze-svg 
             blaze-textual 
             bloodhound 
             bloomfilter 
             bmp 
             bool-extras 
             bound 
             bower-json 
             boxes 
             brainfuck 
             broadcast-chan 
             bson 
             #btrfs 
             buffer-builder 
             bumper 
             byteable 
             bytedump 
             byteorder 
             bytes 
             bytestring-builder 
             bytestring-conversion 
             bytestring-lexing 
             bytestring-mmap 
             bytestring-progress 
             bytestring-read 
             bytestring-trie 
             bzlib 
             bzlib-conduit 
             #c2hs 
             cabal-debian 
             cabal-file-th 
             #cabal-install 
             cabal-rpm 
             cabal-src 
             cairo 
             cartel 
             case-insensitive 
             cases 
             cassava 
             cautious-file 
             cayley-client 
             cereal 
             cereal-conduit 
             cereal-vector 
             cgi 
             charset 
             check-email 
             checkers 
             chell 
             chell-quickcheck 
             chunked-data 
             cipher-aes 
             cipher-aes128 
             cipher-blowfish 
             cipher-camellia 
             cipher-des 
             cipher-rc4 
             circle-packing 
             clash-ghc 
             clash-lib 
             clash-prelude 
             clash-systemverilog 
             clash-verilog 
             clash-vhdl 
             classy-prelude 
             classy-prelude-conduit 
             classy-prelude-yesod 
             clay 
             clientsession 
             clock 
             clustering 
             cmark 
             cmdargs 
             code-builder 
             codex 
             colour 
             comonad 
             comonad-transformers 
             comonads-fd 
             compdata 
             composition 
             composition-extra 
             compressed 
             concatenative 
             concurrent-extra 
             concurrent-supply 
             cond 
             conduit 
             conduit-combinators 
             conduit-extra 
             configurator 
             connection 
             constraints 
             consul-haskell 
             containers-unicode-symbols 
             contravariant 
             control-bool 
             control-monad-free 
             control-monad-loop 
             convertible 
             cookie 
             country-codes 
             courier 
             cpphs 
             cprng-aes 
             cpu 
             cql 
             cql-io 
             crackNum 
             criterion 
             cron 
             crypto-api 
             crypto-api-tests 
             crypto-cipher-tests 
             crypto-cipher-types 
             crypto-numbers 
             crypto-pubkey 
             crypto-pubkey-types 
             crypto-random 
             crypto-random-api 
             cryptocipher 
             cryptohash 
             cryptohash-conduit 
             cryptohash-cryptoapi 
             cryptol 
             cryptonite 
             css-text 
             csv 
             csv-conduit 
             cubicspline 
             curl 
             data-accessor 
             data-accessor-mtl 
             data-binary-ieee754 
             data-default 
             data-default-class 
             data-default-instances-base 
             data-default-instances-containers 
             data-default-instances-dlist 
             data-default-instances-old-locale 
             data-hash 
             data-inttrie 
             data-lens-light 
             data-memocombinators 
             data-ordlist 
             data-reify 
             datadog 
             dbus 
             #debian 
             deepseq-generics 
             dependent-map 
             dependent-sum 
             dependent-sum-template 
             derive 
             descriptive 
             diagrams 
             diagrams-builder 
             diagrams-cairo 
             diagrams-contrib 
             diagrams-core 
             diagrams-haddock 
             diagrams-html5 
             diagrams-lib 
             diagrams-postscript 
             diagrams-rasterific 
             diagrams-solve 
             diagrams-svg 
             dice 
             diff3 
             digest 
             digestive-functors 
             digestive-functors-aeson 
             digestive-functors-lucid 
             digits 
             dimensional 
             direct-sqlite 
             directory-tree 
             disk-free-space 
             distributive 
             djinn-ghc 
             djinn-lib 
             dlist 
             dlist-instances 
             dns 
             dockerfile 
             doctest 
             double-conversion 
             dual-tree 
             easy-file 
             ede 
             edit-distance 
             editor-open 
             effect-handlers 
             either 
             ekg-core 
             elm-core-sources 
             email-validate 
             enclosed-exceptions 
             engine-io 
             engine-io-growler 
             entropy 
             enumerator 
             eq 
             equivalence 
             erf 
             errors 
             esqueleto 
             ether 
             event 
             exception-mtl 
             exception-transformers 
             exceptional 
             exceptions 
             executable-hash 
             executable-path 
             exhaustive 
             expiring-cache-map 
             extensible-exceptions 
             extra 
             #fast-builder 
             #fast-logger 
             fay 
             fay-base 
             fay-builder 
             fay-dom 
             fay-jquery 
             fay-text 
             fay-uri 
             fb 
             fb-persistent 
             fclabels 
             fdo-notify 
             feature-flags 
             feed 
             fgl 
             file-embed 
             #file-location 
             filelock 
             filemanip 
             fingertree 
             fingertree-psqueue 
             fixed 
             fixed-list 
             fixed-vector 
             fixed-vector-hetero 
             flexible-defaults 
             flock 
             flow 
             flowdock 
             fmlist 
             focus 
             foldl 
             force-layout 
             foreign-store 
             formatting 
             free 
             #freenect 
             frisby 
             fsnotify 
             fuzzcheck 
             gd 
             generic-aeson 
             generic-deriving 
             generic-xmlpickler 
             generics-sop 
             geniplate-mirror 
             getopt-generics 
             ghc-events 
             ghc-mtl 
             ghc-parser 
             ghc-paths 
             ghc-syb-utils 
             ghc-tcplugins-extra 
             ghc-typelits-natnormalise 
             #ghcid 
             gio 
             gipeda 
             # git-annex 
             gitlib 
             gitlib-libgit2 
             gitlib-test 
             gitrev 
             gitson 
             #gl 
             glib 
             #gnuidn 
             #gnutls 
             graph-core 
             graph-wrapper 
             graphs 
             gravatar 
             groundhog 
             groundhog-mysql 
             groundhog-postgresql 
             groundhog-sqlite 
             groundhog-th 
             groupoids 
             groups 
             growler 
             gsasl 
             #gtk 
             #gtk2hs-buildtools 
             #gtk3 
             hPDB 
             hackage-db 
             hackage-mirror 
             haddock-api 
             haddock-library 
             hakyll 
             half 
             hamlet 
             happstack-server 
             happy 
             hashable 
             hashable-extras 
             hashmap 
             hashtables 
             haskeline 
             haskell-lexer 
             haskell-names 
             haskell-neo4j-client 
             haskell-packages 
             haskell-spacegoo 
             haskell-src 
             haskell-src-exts 
             haskell-src-meta 
             haskintex 
             hasql 
             hasql-backend 
             hasql-postgres 
             hastache 
             haxr 
             hbeanstalk 
             hdaemonize 
             hdevtools 
             hdocs 
             heap 
             heaps 
             hebrew-time 
             hedis 
             heist 
             here 
             heredoc 
             hex 
             hexpat 
             hexstring 
             hflags 
             hfsevents 
             # hid                
             highjson 
             highlighting-kate 
             #hindent #- emacs - gnutls - autogen-5.18.6 - gnutls - guile 
             hinotify 
             hint 
             histogram-fill 
             hit 
             hjsmin 
             hledger 
             hledger-lib 
             hledger-web 
             hlibgit2 
             hlibsass 
             hlint 
             hmatrix 
             hmatrix-gsl 
             hmatrix-gsl-stats 
             hmatrix-repa 
             hoauth2 
             holy-project 
             hoogle 
             hostname 
             hostname-validate 
             hourglass 
             hpc-coveralls 
             hprotoc 
             hs-bibutils 
             hsass 
             hscolour 
             hse-cpp 
             hsebaysdk 
             hsemail 
             #hsignal 
             hslogger 
             hslua 
             hspec 
             hspec-attoparsec 
             hspec-contrib 
             hspec-core 
             hspec-discover 
             hspec-expectations 
             hspec-jenkins 
             hspec-meta 
             hspec-smallcheck 
             hspec-snap 
             hspec-wai 
             hspec-wai-json 
             hspec-webdriver 
             hstatistics 
             hstatsd 
             hsyslog 
             html 
             html-conduit 
             http-client 
             http-client-tls 
             http-common 
             http-conduit 
             http-date 
             http-media  
             #http-reverse-proxy 
             http-streams 
             http-types 
             http2 
             hvect 
             hweblib 
             hxt 
             hxt-charproperties 
             hxt-css 
             hxt-curl 
             hxt-expat 
             hxt-http 
             hxt-pickle-utils 
             hxt-regex-xmlschema 
             hxt-relaxng 
             hxt-tagsoup 
             hxt-unicode 
             hyperloglog 
             hyphenation 
             ide-backend 
             ide-backend-common 
             ide-backend-rts 
             ide-backend-server 
             ieee754 
             ignore 
             ihaskell 
             ihaskell-aeson 
             ihaskell-basic 
             #ihaskell-blaze 
             ihaskell-charts 
             #ihaskell-diagrams 
             ihaskell-hatex 
             ihaskell-juicypixels 
             ihaskell-magic 
             ihaskell-rlangqq 
             imagesize-conduit 
             immortal 
             # include-file 
             incremental-parser 
             indents 
             inflections 
             ini 
             integration 
             interpolate 
             interpolatedstring-perl6 
             intervals 
             invariant 
             io-choice 
             io-manager 
             io-memoize 
             io-streams 
             ip6addr 
             iproute 
             ipython-kernel 
             islink 
             iso3166-country-codes 
             iso639 
             iterable 
             jmacro 
             jmacro-rpc 
             jmacro-rpc-happstack 
             jmacro-rpc-snap 
             jose-jwt 
             js-flot 
             js-jquery 
             json 
             json-autotype 
             json-builder 
             json-schema 
             jwt 
             kan-extensions 
             kdt 
             #keter 
             keycode 
             keys 
             kmeans 
             knob 
             koofr-client 
             kure 
             lambdabot 
             lambdabot-core 
             lambdabot-haskell-plugins 
             lambdabot-irc-plugins 
             lambdabot-misc-plugins 
             lambdabot-novelty-plugins 
             lambdabot-reference-plugins 
             lambdabot-social-plugins 
             lambdabot-trusted 
             language-c 
             language-c-quote 
             language-ecmascript 
             language-glsl 
             language-haskell-extract 
             language-java 
             language-javascript 
             largeword 
             lattices 
             lazy-csv 
             lazysmallcheck 
             lca 
             lens 
             lens-action 
             lens-aeson 
             lens-family 
             lens-family-core 
             lens-family-th 
             lens-simple 
             lexer-applicative 
             lhs2tex 
             libgit 
             #libnotify 
             librato 
             libxml-sax 
             lifted-async 
             lifted-base 
             linear 
             linear-accelerate 
             #linux-file-extents 
             #linux-namespaces 
             list-fusion-probe 
             list-t 
             loch-th 
             log-domain 
             logging-facade 
             logict 
             loop 
             lrucache 
             ltext 
             lucid 
             lucid-svg 
             lzma-conduit 
             machines 
             machines-directory 
             machines-io 
             machines-process 
             magic 
             mainland-pretty 
             managed 
             mandrill 
             mangopay 
             map-syntax 
             markdown 
             markup 
             math-functions 
             matrices 
             matrix 
             maximal-cliques 
             mbox 
             memcached-binary 
             memoize 
             memory 
             mersenne-random-pure64 
             messagepack 
             messagepack-rpc 
             metrics 
             microlens 
             microlens-ghc 
             microlens-mtl 
             microlens-th 
             mime-mail 
             mime-mail-ses 
             mime-types 
             misfortune 
             missing-foreign 
             mmap 
             mmorph 
             mockery 
             monad-control 
             monad-coroutine 
             monad-extras 
             monad-journal 
             monad-logger 
             monad-logger-json 
             monad-logger-syslog 
             monad-loops 
             monad-par 
             monad-par-extras 
             monad-parallel 
             monad-peel 
             monad-primitive 
             monad-products 
             monad-skeleton 
             monad-st 
             monad-stm 
             monad-unlift 
             monadLib 
             monadcryptorandom 
             monadic-arrays 
             monads-tf 
             mongoDB 
             mono-traversable 
             monoid-extras 
             monoid-subclasses 
             monoidal-containers 
             #msi-kb-backlit 
             mstate 
             mtl 
             mtl-compat 
             mtl-prelude 
             mueval 
             multiarg 
             multimap 
             multipart 
             multiset 
             murmur-hash 
             mutable-containers 
             mwc-random 
             mysql 
             mysql-simple 
             nanospec 
             nationstates 
             nats 
             ndjson-conduit 
             neat-interpolation 
             network 
             network-anonymous-i2p 
             network-anonymous-tor 
             network-attoparsec 
             network-carbon 
             network-conduit-tls 
             network-info 
             network-multicast 
             #network-protocol-xmpp 
             network-simple 
             network-transport 
             network-uri 
             newtype 
             newtype-generics 
             nonce 
             nsis 
             numbers 
             numeric-extras 
             numtype 
             objective 
             oeis 
             old-locale 
             old-time 
             opaleye 
             openpgp-asciiarmor 
             openssl-streams 
             operational 
             operational-class 
             optional-args 
             options 
             optparse-applicative 
             optparse-simple 
             #osdkeys 
             pager 
             pagerduty 
             palette 
             pandoc 
             pandoc-citeproc 
             pandoc-types 
             pango 
             parallel 
             parallel-io 
             parseargs 
             parsec 
             parsers 
             partial-handler 
             path 
             path-pieces 
             patience 
             pattern-arrows 
             pcre-heavy 
             pcre-light 
             pdfinfo 
             pem 
             persistent 
             persistent-mongoDB 
             persistent-mysql 
             persistent-postgresql 
             persistent-refs 
             persistent-sqlite 
             persistent-template 
             phantom-state 
             #phash 
             picoparsec 
             pipes 
             pipes-aeson 
             pipes-attoparsec 
             pipes-bgzf 
             pipes-binary 
             pipes-bytestring 
             pipes-cliff 
             pipes-concurrency 
             pipes-fastx 
             pipes-group 
             pipes-http 
             pipes-illumina 
             pipes-network 
             pipes-parse 
             pipes-safe 
             pipes-text 
             pipes-wai 
             placeholders 
             plot 
             #plot-gtk 
             #plot-gtk3 
             pointed 
             poly-arity 
             polyparse 
             #posix-realtime 
             post-mess-age 
             postgresql-binary 
             postgresql-libpq 
             postgresql-simple 
             postgresql-simple-url 
             pqueue 
             pred-trie 
             prednote 
             prefix-units 
             prelude-extras 
             presburger 
             pretty-class 
             pretty-show 
             prettyclass 
             primes 
             primitive 
             process-extras 
             product-profunctors 
             profunctor-extras 
             profunctors 
             project-template 
             prometheus-client 
             prometheus-metrics-ghc 
             protocol-buffers 
             protocol-buffers-descriptor 
             psqueues 
             pure-io 
             pureMD5 
             #purescript 
             pwstore-fast 
             quandl-api 
             quickcheck-assertions 
             quickcheck-instances 
             quickcheck-io 
             quickcheck-unicode 
             rainbow 
             rainbox 
             random 
             random-fu 
             random-shuffle 
             random-source 
             range 
             rasterific-svg 
             raw-strings-qq 
             redis-io 
             redis-resp 
             reducers 
             ref-fd 
             refact 
             reflection 
             regex-applicative 
             regex-base 
             regex-compat 
             regex-pcre 
             regex-pcre-builtin 
             regex-posix 
             regex-tdfa 
             regex-tdfa-rc 
             repa 
             repa-algorithms 
             #repa-devil 
             repa-io 
             reroute 
             resource-pool 
             resourcet 
             rest-client 
             rest-core 
             rest-gen 
             rest-happstack 
             rest-snap 
             rest-stringmap 
             rest-types 
             rest-wai 
             rethinkdb-client-driver 
             retry 
             rev-state 
             rfc5051 
             runmemo 
             rvar 
             safe 
             safecopy 
             sandi 
             sbv 
             scalpel 
             scientific 
             scotty 
             #sdl2 
             #second-transfer 
             securemem 
             semigroupoid-extras 
             semigroupoids 
             semigroups 
             semver 
             sendfile 
             seqalign 
             seqloc 
             serf 
             servant 
             servant-JuicyPixels 
             servant-client 
             servant-docs 
             servant-jquery 
             servant-pandoc 
             servant-server 
             serversession 
             serversession-backend-acid-state 
             serversession-backend-persistent 
             serversession-backend-redis 
             serversession-frontend-snap 
             serversession-frontend-wai 
             serversession-frontend-yesod 
             set-extra 
             set-monad 
             setenv 
             setlocale 
             shake 
             shake-language-c 
             shakespeare 
             shell-conduit 
             shelltestrunner 
             shelly 
             shortcut-links 
             show 
             silently 
             simple-reflect 
             simple-sendfile 
             singletons 
             siphash 
             skein 
             slave-thread 
             smallcheck 
             smoothie 
             smtLib 
             smtp-mail 
             snap 
             snap-core 
             snap-server 
             snaplet-fay 
             snmp 
             snowflake 
             socket-io 
             socks 
             sodium 
             sourcemap 
             spdx 
             speculation 
             sphinx 
             splice 
             split 
             spoon 
             sqlite-simple 
             srcloc 
             stack 
             stackage 
             stackage-build-plan 
             stackage-cabal 
             stackage-cli 
             stackage-install 
             stackage-metadata 
             stackage-sandbox 
             stackage-setup 
             stackage-types 
             stackage-update 
             stackage-upload 
             stateref 
             statestack 
             static-canvas 
             statistics 
             statistics-linreg 
             stm 
             stm-chans 
             stm-conduit 
             stm-containers 
             stm-delay 
             stm-stats 
             storable-complex 
             storable-endian 
             streaming-commons 
             streams 
             strict 
             string-class 
             string-combinators 
             string-conversions 
             stringable 
             stringbuilder 
             stringsearch 
             stylish-haskell 
             svg-tree 
             swagger 
             syb 
             symbol 
             system-argv0 
             system-fileio 
             system-filepath 
             system-posix-redirect 
             tabular 
             tagged 
             tagged-binary 
             tagshare 
             tagsoup 
             tagstream-conduit 
             tar 
             tardis 
             tasty 
             tasty-ant-xml 
             tasty-golden 
             tasty-hspec 
             tasty-hunit 
             tasty-kat 
             tasty-quickcheck 
             tasty-rerun 
             tasty-silver 
             tasty-smallcheck 
             tasty-th 
             template 
             temporary 
             temporary-rc 
             terminal-progress-bar 
             terminal-size 
             terminfo 
             test-framework 
             test-framework-hunit 
             test-framework-quickcheck2 
             test-framework-th 
             testing-feat 
             texmath 
             text 
             text-binary 
             text-format 
             text-icu 
             text-manipulate 
             text-show 
             tf-random 
             th-desugar 
             th-expand-syns 
             th-extras 
             th-lift 
             th-orphans 
             th-reify-many 
             threads 
             through-text 
             thumbnail-plus 
             thyme 
             time-compat 
             time-lens 
             time-locale-compat 
             timeit 
             timerep 
             timezone-olson 
             timezone-series 
             tinylog 
             tls 
             tls-debug 
             token-bucket 
             #torrent 
             tostring 
             transformers-base 
             transformers-compat 
             transformers-lift 
             traverse-with-class 
             tree-view 
             trifecta 
             tttool 
             tuple 
             tuples-homogenous-h98 
             turtle 
             twitter-feed 
             type-eq 
             type-level-numbers 
             type-list 
             types-compat 
             unbound-generics 
             unbounded-delays 
             union-find 
             uniplate 
             unix-compat 
             unix-time 
             unlambda 
             unordered-containers 
             uri-bytestring 
             uri-encode 
             uri-templater 
             url 
             urlpath 
             users 
             users-persistent 
             users-postgresql-simple 
             users-test 
             utf8-light 
             utf8-string 
             uu-interleaved 
             uu-parsinglib 
             uuid 
             uuid-types 
             validate-input 
             vault 
             vector 
             vector-algorithms 
             vector-binary-instances 
             vector-buffer 
             vector-instances 
             vector-space 
             vector-space-points 
             vector-th-unbox 
             vhd 
             void 
             wai 
             wai-app-static 
             wai-conduit 
             wai-cors 
             wai-eventsource 
             wai-extra 
             wai-handler-launch 
             wai-logger 
             wai-middleware-consul 
             wai-middleware-crowd 
             wai-middleware-prometheus 
             wai-middleware-static 
             wai-middleware-throttle 
             wai-predicates 
             wai-route 
             wai-routes 
             wai-routing 
             wai-session 
             wai-websockets 
             waitra 
             warp 
             warp-tls 
             web-fpco 
             web-routing 
             webdriver 
             webdriver-angular 
             webpage 
             websockets 
             witherable 
             wizards 
             wl-pprint 
             wl-pprint-extras 
             wl-pprint-terminfo 
             wl-pprint-text 
             word8 
             wordpass 
             wrap 
             wreq 
             x509 
             x509-store 
             x509-system 
             x509-validation 
             xenstore 
             xformat 
             xhtml 
             xlsior 
             #xlsx 
             xml 
             xml-conduit 
             xml-hamlet 
             xml-lens 
             xml-to-json 
             xml-to-json-fast 
             xml-types 
             xmlgen 
             xmlhtml 
             xss-sanitize 
             yackage 
             yaml 
             yesod 
             yesod-auth 
             yesod-auth-account 
             yesod-auth-basic 
             yesod-auth-deskcom 
             yesod-auth-fb 
             yesod-auth-hashdb 
             yesod-auth-oauth 
             yesod-auth-oauth2 
             yesod-bin 
             yesod-core 
             yesod-default 
             yesod-eventsource 
             yesod-fay 
             yesod-fb 
             yesod-form 
             yesod-gitrepo 
             yesod-gitrev 
             yesod-mangopay 
             yesod-newsfeed 
             yesod-persistent 
             yesod-sitemap 
             yesod-static 
             yesod-static-angular 
             yesod-table 
             yesod-test 
             yesod-text-markdown 
             yesod-websockets 
             zero 
             zeromq4-haskell 
             zip-archive 
             zlib 
             zlib-bindings 
             zlib-enum 
             #zlib-lens 
    ]